Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    
    config.vm.provider "virtualbox" do |vb|
       vb.memory = "2048"
       #vb.gui = true

       vb.customize ["modifyvm", :id, "--bioslogofadein","off"]
       vb.customize ["modifyvm", :id, "--bioslogofadeout","off"]
       vb.customize ["modifyvm", :id, "--bioslogodisplaytime", 0]
       vb.customize ["modifyvm", :id, "--vrde","on"]
       vb.customize ["modifyvm", :id, "--vrdeport", 3389]
       vb.customize ["setextradata", :id, "CustomVideoMode1", "1680x1050x32"]

       vb.customize [ "modifyvm", :id, "--uart1", "0x03f8", "4" ]
	   vb.customize [ "modifyvm", :id, "--uartmode1", "file", Vagrant::Util::Platform.windows? ? "NUL" : "/dev/null" ]
    end

    config.vm.provision "shell",
        path: "scripts/provision.sh"
end