# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
BOX_NAME = "centos/7"
JOIN_SCRIPT = "join-to-cluster.sh"

# Setup constants
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Use vagrant-env plugin if available
  if Vagrant.has_plugin?("vagrant-env")
    config.env.load('.env.local', '.env') # enable the plugin
  end

  # Number of worker nodes to provision
  WORKER_NODES = env_or_default_int('WORKER_NODES', 2)

  # To access your cluster from the host, set the following variable to true
  ACCESS_FROM_HOST = env_or_default_bool('ACCESS_FROM_HOST', false)

  # Master Node IP adress
  MASTER_IP = env_or_default('MASTER_IP', '192.168.10.100')

  # Worker Node Memory for the VMs (4GB)
  WORKER_MEMORY = env_or_default_int('WORKER_MEMORY', 4096)

  # Master Node Memory for the VMs (2GB)
  MASTER_MEMORY = env_or_default_int('MASTER_MEMORY', 2048)

  # Worker Node CPU (1)
  WORKER_CPU = env_or_default_int('WORKER_MEMORY', 1)

  # Master Node CPU (2)
  MASTER_CPU = env_or_default_int('MASTER_MEMORY', 2)

  # To install Helm, set the following variable to true
  INSTALL_HELM = env_or_default_bool('INSTALL_HELM', false)

  # To install Nginx, set the following variable to true
  INSTALL_NGINX = env_or_default_bool('INSTALL_NGINX', false)

  # To install Operator Lifecycle Manager, set the following variable to true
  INSTALL_OLM = env_or_default_bool('INSTALL_OLM', false)

  # Comma seperated list of operators to install
  # Use install yaml name without .yaml extension.
  # i.e.: For grafana operator with url https://operatorhub.io/install/grafana-operator.yaml use 'grafana-operator'
  INSTALL_OPERATORS = env_or_default('INSTALL_OPERATORS', '')
end

# Convenience methods
def env_or_default(key, default)
  ENV[key] && ! ENV[key].empty? ? ENV[key] : default
end
  
def env_or_default_int(key, default)
  env_or_default(key, default).to_i
end
  
def env_or_default_bool(key, default)
  env_or_default(key, default).to_s.downcase == 'true'
end

Vagrant.configure(2) do |config|
    config.vm.box = BOX_NAME

    # Master Node
    config.vm.define "master", primary: true do |master|
        master.vm.hostname = "master.vagrant.vm"
        master.vm.network "private_network", ip: MASTER_IP

        master.vm.provider "virtualbox" do |vb, config|
          vb.memory = MASTER_MEMORY
          vb.cpus = MASTER_CPU
          config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

          vb.customize ["modifyvm", :id, "--groups", "/Kubernetes"]
          vb.customize ["modifyvm", :id, "--audio", "none"]
        end

        master.vm.provider "libvirt" do |lv, config|
          lv.memory = MASTER_MEMORY
          lv.cpus = MASTER_CPU
          config.vm.synced_folder ".", "/vagrant", type: "nfs"
        end

        if Vagrant.has_plugin?("vagrant-hosts")
            master.vm.provision :hosts, :sync_hosts => true
        end

        if ACCESS_FROM_HOST
            # Bind kubernetes admin port to access from host
            master.vm.network "forwarded_port", guest: 6443, host: 6443
        end

        args = []
        args.push("--masterIp", MASTER_IP)
        args.push("--joinScript", JOIN_SCRIPT)
        args.push("--installOperators", INSTALL_OPERATORS)
        args.push("--accessFromHost") if ACCESS_FROM_HOST
        args.push("--installHelm") if INSTALL_HELM
        args.push("--installNginx") if INSTALL_NGINX
        args.push("--installOLM") if INSTALL_OLM

        master.vm.provision "shell",
           path: "scripts/setup-master.sh",
           args: args
    end

    # Worker Nodes
    (1..WORKER_NODES).each do |i|
        config.vm.define "worker#{i}" do |worker|
           worker.vm.hostname = "worker#{i}.vagrant.vm"

           worker.vm.provider "virtualbox" do |vb, config|
            vb.memory = WORKER_MEMORY
            vb.cpus = WORKER_CPU

            config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

            vb.customize ["modifyvm", :id, "--groups", "/Kubernetes"]
            vb.customize ["modifyvm", :id, "--audio", "none"]
           end

           worker.vm.provider "libvirt" do |lv, config|
            lv.memory = WORKER_MEMORY
            lv.cpus = WORKER_CPU
            config.vm.synced_folder ".", "/vagrant", type: "nfs"
           end

           ip_blocks = MASTER_IP.split(".")
           ip_blocks[3] = ip_blocks[3].to_i + i
           ip = ip_blocks.join(".")

           worker.vm.network "private_network", ip: ip

           if Vagrant.has_plugin?("vagrant-hosts")
             worker.vm.provision :hosts, :sync_hosts => true
           end


           args = []
           args.push("--joinScript", JOIN_SCRIPT)

           worker.vm.provision "shell",
              path: "scripts/setup-worker.sh",
              args: args
        end
    end

    config.vm.provision "shell",
        path: "scripts/provision.sh"
end